import React from 'react'
import Table from 'react-bootstrap/Table'

export const ScoreBoard = () => (
    <React.Fragment>
        <Table responsive="xl" striped bordered hover variant="dark">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Jetha</th>
                    <th>Babita</th>
                    <th>Iyer</th>
                    <th>Baka</th>
                    <th>Tapu</th>
                    <th>Bapuji</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>69</td>
                    <td>69</td>
                    <td>69</td>
                    <td>69</td>
                    <td>69</td>
                    <td>69</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>5</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>6</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>7</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>8</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>9</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>10</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                </tr>
                <tr>
                    <td>Total</td>
                    <td>69</td>
                    <td>69</td>
                    <td>69</td>
                    <td>69</td>
                    <td>69</td>
                    <td>69</td>
                </tr>
            </tbody>
        </Table>
    </React.Fragment>
)